version: "3.9"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "clickhouse-client --query='SELECT 1' || exit 1" ]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 30s

  aiohttp_app:
    container_name: aiohttp_app
    build: .
    depends_on:
      clickhouse:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
    volumes:
      - ./src:/app/src

# Объявляем volume
volumes:
  clickhouse-data:
